import { Inter } from "next/font/google";

import "./../public/css/globals.css";
import { PageContent } from "@/components/static/pagecontent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <PageContent>{children}</PageContent>
      </body>
    </html>
  );
}
