"use client";

import { Inter } from "next/font/google";
import { Providers } from "./providers";

import "./../public/css/globals.css";
import { Header } from "@/components/static/header";
import { Footer } from "@/components/static/footer";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [headerHeight, setHeaderHeight] = useState(0);
  const [footerHeight, setFooterHeight] = useState(0);

  return (
    <html lang="en">
      <body style={{ minHeight: "100vh" }}>
        <Header />
        <Providers>{children}</Providers>
        <Footer />
      </body>
    </html>
  );
}
